# Generated by Django 3.2.3 on 2022-06-01 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requerimientos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('validez', models.IntegerField()),
                ('status', models.BooleanField(default=True, help_text='Para desactivar el convenio, deshabilite esta casilla.')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.requerimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(max_length=20, verbose_name='Código Externo')),
                ('nombre', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True, help_text='Para desactivar el insumo, deshabilite esta casilla.')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True, help_text='para desactivar el tipo de Insumo, deshabilite esta casilla.')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConvenioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Para desactivar el detalle del convenio, deshabilite esta casilla.')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epps.convenio')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epps.insumo')),
            ],
        ),
        migrations.AddField(
            model_name='convenio',
            name='tipo_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epps.tipoinsumo'),
        ),
    ]
