# Generated by Django 3.2.3 on 2022-06-02 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0002_initial'),
        ('epps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Para desactivar la asignación del convenio, deshabilite esta casilla.')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tipoinsumo',
            options={},
        ),
        migrations.RemoveField(
            model_name='convenio',
            name='requerimiento',
        ),
        migrations.AddField(
            model_name='convenio',
            name='insumo',
            field=models.ManyToManyField(help_text='Seleccione uno o mas insumos para este convenio.', to='epps.Insumo'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='nombre',
            field=models.CharField(default='prueba', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='costo',
            field=models.FloatField(default='5'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConvenioDetalle',
        ),
        migrations.AddField(
            model_name='asignacionconvenio',
            name='convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epps.convenio'),
        ),
        migrations.AddField(
            model_name='asignacionconvenio',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.requerimiento'),
        ),
    ]
