# Generated by Django 3.2.3 on 2022-06-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('epps', '0002_auto_20220602_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='tipo_insumo',
        ),
        migrations.AddField(
            model_name='convenio',
            name='cliente',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convenio',
            name='planta',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='clientes.planta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo_insumo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='epps.tipoinsumo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AsignacionConvenio',
        ),
    ]
