"""Contratos urls."""

# Django
from django.urls import path
from django.contrib.auth import views as auth_views
from contratos import views


urlpatterns = [
    # Plantillas
    path(
        route='plantilla/list/',
        view=views.PlantillaListView.as_view(),
        name="list-plantilla"
    ),
    path(
        route='plantilla/create/',
        view=views.create_plantilla,
        name="create-plantilla"
    ),
    path(
        route='<int:plantilla_id>/plantilla/update/',
        view=views.update_plantilla,
        name="update-plantilla"
    ),
    path(
        route='<int:object_id>/plantilla/delete/',
        view=views.delete_plantilla,
        name="delete-plantilla"
    ),
    # Parámetros de Puesta a Disposición - Fórmula
    path(
        route='puesta_disposicion',
        view=views.PuestaDisposicionView.as_view(),
        name='puesta-disposicion'
     ),
    # tipo de contratos
    path(
        route='tipo_contratos',
        view=views.TipoContratosView.as_view(),
        name='tipo-contratos'
     ),
    # Requerimiento Contrato
    path(
        route='<int:requerimiento_trabajador_id>/create_contrato/',
        view=views.ContratoIdView.as_view(),
        name="create_contrato"
    ),
    # Contratos
    path(
        route='list/',
        view=views.ContratoListView.as_view(),
        name="list"
    ),
    path(
        route='create/',
        view=views.create,
        name="create"
    ),
    path(
        route='<int:contrato_id>/update_contrato/',
        view=views.update_contrato,
        name="update_contrato"
    ),
    path(
        route='<int:object_id>/delete/',
        view=views.delete,
        name="delete"
    ),
    path(
        'exportar_excel',
        view=views.exportar_excel_contrato,
        name="exportar_excel"
    ),
    path(
        'exportar_excel_pendiente',
        view=views.exportar_excel_contrato_pendiente,
        name="exportar_excel_pendiente"
    ),
    path(
        'exportar_excel_normal',
        view=views.exportar_excel_contrato_normal,
        name="exportar_excel_normal"
    ),
    path(
        route='<str:aprobacion>/aprobacion_masiva/',
        view=views.aprobacion_masiva,
        name="aprobacion_masiva"
    ),
    path(
        route='<str:aprobacion>/aprobacion_masiva_anexo/',
        view=views.aprobacion_masiva_anexo,
        name="aprobacion_masiva_anexo"
    ),
    path(
        route='solicitudes/',
        view=views.SolicitudContrato.as_view(),
        name="solicitudes-contrato"
    ),
    path(
        route='completas',
        view=views.ContratoCompletaListView.as_view(),
        name="completas-contrato"
    ),
    path('buscarContrato', views.buscar_contrato),
    path(
        route='bajas/',
        view=views.BajaContrato.as_view(),
        name="bajas-contrato"
    ),
    path(
        route='<int:contrato_id>/solicitudes-pendientes/',
        view=views.solicitudes_pendientes,
        name="solicitudes-pendientes"
    ),
    path(
        route='<int:contrato_id>/solicitudes-pendientes-baja/',
        view=views.solicitudes_pendientes_baja,
        name="solicitudes-pendientes-baja"
    ),
    path(
        route='<int:contrato_id>/baja_contrato/',
        view=views.baja_contrato,
        name="baja_contrato"
    ),
    path(
        route='bajadas',
        view=views.ContratoBajaListView.as_view(),
        name="bajadas-contrato"
    ),
    path('buscarBajaContrato', views.buscar_baja_contrato),
    path(
        route='miscontratos/',
        view=views.ContratoMis.as_view(),
        name="miscontratos"
    ),
    path(
        route='<int:pk>/detail/',
        view=views.ContratoDetailView.as_view(),
        name="detail"
    ),
    path(
        route='<int:contrato_id>/enviar_revision_contrato/',
        view=views.enviar_revision_contrato,
        name="enviar_revision_contrato"
    ),
    # Anexos
    path(
        route='anexo/create/',
        view=views.create_anexo,
        name="create-anexo"
    ),
    path(
        route='<int:anexo_id>/update_anexo/',
        view=views.update_anexo,
        name="update_anexo"
    ),
    path(
        route='<int:object_id>/delete_anexo/',
        view=views.delete_anexo,
        name="delete-anexo"
    ),
    path(
        route='anexo/solicitud/',
        view=views.SolicitudAnexo.as_view(),
        name="solicitud-anexo"
    ),
    path(
        route='<int:anexo_id>/enviar_revision_anexo/',
        view=views.enviar_revision_anexo,
        name="enviar_revision_anexo"
    ),
    path(
        'exportar_excel_pendiente_anexo',
        view=views.exportar_excel_anexo_pendiente,
        name="exportar_excel_pendiente_anexo"
    ),
    path(
        route='anexo/exportar_excel_normal_anexo',
        view=views.exportar_excel_anexo_normal,
        name="exportar_excel_normal_anexo"
    ),
    path(
        route='<int:anexo_id>/solicitudes-pendientes-anexo/',
        view=views.solicitudes_pendientes_anexo,
        name="solicitudes_pendientes_anexo"
    ),
    path(
        route='<int:anexo_id>/solicitudes-pendientes-anexo-baja/',
        view=views.solicitudes_pendientes_anexo_baja,
        name="solicitudes_pendientes_anexo_baja"
    ),
    path(
        route='anexo/list',
        view=views.AnexoCompletaListView.as_view(),
        name="list-anexo"
    ),
    path('anexo/buscarAnexo', views.buscar_anexo),
    path(
        route='anexo/baja/',
        view=views.BajaAnexo.as_view(),
        name="baja-anexo"
    ),
    path(
        route='<int:anexo_id>/baja_contrato_anexo/',
        view=views.baja_contrato_anexo,
        name="baja_contrato_anexo"
    ),
    path(
        route='anexo/bajada',
        view=views.AnexoBajaListView.as_view(),
        name="bajada-anexo"
    ),
    path('anexo/buscarBajaAnexo', views.buscar_baja_anexo),
    # Carta de Término
    path(
        route='carta_termino/',
        view=views.carta_termino,
        name="carta-termino"
    ),
    path(
        route='<int:contrato_id>/generar_firma/',
        view=views.generar_firma_contrato,
        name='generar_firma'
    ),
    path(
        route='<int:id>/firmar/',
        view=views.ContratoFirmarView.as_view(),
        name='firmar'
    ),
    #baja contrato de completas
    path(
        route='<int:contrato_id>/baja_contrato_completa/',
        view=views.contrato_baja_completa,
        name="contrato_baja_completa"
    ),
    path(
        route='<slug:id>/generar_firma/firmarr/',
        view=auth_views.PasswordResetDoneView.as_view(),
        name='generar_firma_done'
    ),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
]
