# Generated by Django 3.2.3 on 2022-08-11 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on  which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on  which the object was last modified.', verbose_name='modified at')),
                ('nombre', models.CharField(max_length=60)),
                ('sub_tipo', models.BooleanField(default=False, help_text='para indicar "Correo y Sistema" habilite esta casilla (True), para indicar "Sistema" deshabilite esta casilla (False).')),
                ('status', models.BooleanField(default=True, help_text='para desactivar el tipo de notificación, deshabilite esta casilla.')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_tipo_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_tipo_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on  which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on  which the object was last modified.', verbose_name='modified at')),
                ('notifica_sistema', models.CharField(max_length=250)),
                ('fecha_notificacion', models.DateField(blank=True, null=True, verbose_name='Fecha Notificación')),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, help_text='Para desactivar el destinatario de la notificación, deshabilite esta casilla.')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_destinatario_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_destinatario_modified_by', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notificaciones.tipo')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
