# Generated by Django 3.2.3 on 2022-03-10 18:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requerimientos', '0003_auto_20220225_1829'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examenes', '0003_alter_requerimiento_requerimiento_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsicologicoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True, help_text='Para desactivar tipo de examenes psicologico, deshabilite esta casilla.')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Psicologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado')], default='R', max_length=1)),
                ('resultado', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=True, help_text='Para desactivar el examen psicologico, deshabilite esta casilla.')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='examenes.examen')),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.planta')),
                ('requerimiento_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='requerimientos.requerimientouser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionPsicologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('R', 'Recomendable'), ('R', 'No Recomendable')], max_length=1)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(max_length=120)),
                ('archivo', models.FileField(upload_to='evaluacionpsicologica/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'])])),
                ('status', models.BooleanField(default=True, help_text='Para desactivar la evaluacion del examen psicologico, deshabilite esta casilla.')),
                ('referido', models.BooleanField(default=False, help_text='Para marcar como referido, habilite esta casilla.')),
                ('Hal2', models.BooleanField(default=False, help_text='Si examen hal2 es requerido , habilite esta casilla.')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.cargo')),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.planta')),
                ('psicologico_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='psicologos.psicologicotipo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on  which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on  which the object was last modified.', verbose_name='modified at')),
                ('tipo', models.CharField(choices=[('SUP', 'Supervisor'), ('TEC', 'Técnico')], default='TEC', max_length=3)),
                ('referido', models.BooleanField(default=False, help_text='Para marcar como referido, habilite esta casilla.')),
                ('Hal2', models.BooleanField(default=False, help_text='Si examen hal2 es requerido , habilite esta casilla.')),
                ('fecha_ingreso_estimada', models.DateField(blank=True, null=True)),
                ('fecha_agenda_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado'), ('E', 'Espera evaluacion'), ('AG', 'Agendado')], default='E', max_length=2)),
                ('obs', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, help_text='Para desactivar la evaluacion del examen psicologico, deshabilite esta casilla.')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.cargo')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psicologos_agenda_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psicologos_agenda_modified_by', to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.planta')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
