# Generated by Django 3.2.3 on 2022-03-10 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psicologos', '0002_evaluacionpsicologico_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='psico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psicologos_evalua', to=settings.AUTH_USER_MODEL),
        ),
    ]
