# Generated by Django 3.2.3 on 2022-03-11 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psicologos', '0003_agenda_psico'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionpsicologico',
            name='psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psico_evaluador', to=settings.AUTH_USER_MODEL),
        ),
    ]
