# Generated by Django 3.2.3 on 2022-05-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on  which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on  which the object was last modified.', verbose_name='modified at')),
                ('tipo', models.CharField(choices=[('SUP', 'Supervisor'), ('TEC', 'Técnico')], default='TEC', max_length=3)),
                ('tipo_evaluacion', models.CharField(choices=[('PSI', 'Psicologia'), ('GEN', 'General')], max_length=3)),
                ('referido', models.BooleanField(default=False, help_text='Para marcar como referido, habilite esta casilla.')),
                ('hal2', models.BooleanField(default=False, help_text='Si examen hal2 es requerido , habilite esta casilla.')),
                ('fecha_ingreso_estimada', models.DateField(blank=True, null=True)),
                ('fecha_agenda_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado'), ('E', 'Espera evaluacion'), ('AG', 'Agendado')], default='E', max_length=2)),
                ('obs', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, help_text='Para desactivar la evaluacion del examen psicologico, deshabilite esta casilla.')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=True, help_text='Para desactivar el bono, deshabilite esta casilla.')),
            ],
        ),
    ]
