# Generated by Django 3.2.3 on 2022-05-23 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamientos', '0001_initial'),
        ('examenes', '0001_initial'),
        ('utils', '0001_initial'),
        ('clientes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centromedico',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.ciudad'),
        ),
        migrations.AddField(
            model_name='centromedico',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.provincia'),
        ),
        migrations.AddField(
            model_name='centromedico',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='bateria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='examenes.bateria'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.cargo'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agendamientos.centromedico'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamientos_agendamiento_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamientos_agendamiento_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.planta'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='psico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pisco', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.trabajador'),
        ),
    ]
