# Generated by Django 3.2.3 on 2022-05-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamientos', '0003_agendamiento_requerimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centromedico',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='centromedico',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='centromedico',
            name='region',
        ),
    ]
