# Generated by Django 3.2.3 on 2022-05-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_centromedico'),
        ('agendamientos', '0004_auto_20220530_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamiento',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='examenes.centromedico'),
        ),
        migrations.DeleteModel(
            name='CentroMedico',
        ),
    ]
